name: "Build kernels 5.10 with KSU Next and susfs"

env:
  CONFIGURATION: "repos_android12-5.10.json"
  OUT_DIR: "out"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    name: "🐂 Parse repos.json"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
    steps:
      - name: "😄 Checkout"
        uses: actions/checkout@v3

      - name: "😆 Generate Matrix"
        id: generate-matrix
        run: |
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          cat  ${{ env.CONFIGURATION }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      kernelDir: ${{ matrix.repos.kernelSource.name }}_${{ matrix.repos.kernelSource.device }}

      kernelName: ${{ matrix.repos.kernelSource.name }}
      kernelRepo: ${{ matrix.repos.kernelSource.repo }}
      kernelBranch: ${{ matrix.repos.kernelSource.branch }}
      kernelDevice: ${{ matrix.repos.kernelSource.device }}

      DEFCONFIG_NAME: ${{ matrix.repos.kernelSource.device }}_defconfig

      withKernelSU: ${{ matrix.repos.withKernelSU }}
        
    steps:
      - name: "⭐ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python3 libarchive-tools repo gzip

      - name: "💫 Get toolchains"
        run: |
          git clone --depth 1 https://github.com/reigadegr/Android-Kernel-Builder
          cd Android-Kernel-Builder
          repo init --depth 1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
          repo sync -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          rm -rf common .repo
          # sed -i 's/return ${RES}/return 0/g' build/_setup_env.sh
          
      - name: "🌟 Clone kernel source => (${{ env.kernelRepo }})"
        run: |
          cd Android-Kernel-Builder
          git clone --recursive --branch $kernelBranch $kernelRepo $kernelName --depth=1
          mv $kernelName common
          rm -rf common/.git
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10 --depth 1
          git clone https://github.com/WildPlusKernel/kernel_patches.git --depth 1
          
      - name: "😋 Update MKernelSU"
        if: ${{ env.withKernelSU == 'true' }}
        run: |
          cd Android-Kernel-Builder
          rm -rf "./KernelSU" 2>/dev/null
          rm -rf "./drivers/kernelsu" 2>/dev/null
          ls
          pwd
          if [ ! -d "./drivers/staging/kernelsu" ]; then
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s main
          fi


      - name: Apply SUSFS Patches KernelSU-Next😇
        run: |
          cd Android-Kernel-Builder

          echo "Applying SUSFS patches..."

          # Copy SUSFS patches
          # [  ! -f ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ] && exit 1      
              
          # cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
          
          [  ! -f  ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ] && exit 1
          cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./common/
          
          [  ! -d ./susfs4ksu/kernel_patches/fs ] && exit 1
          cp ./susfs4ksu/kernel_patches/fs/* ./common/fs/
          
          [  ! -d ./susfs4ksu/kernel_patches/include/linux ] && exit 1
          cp ./susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

          cd ./KernelSU-Next
          echo "Applying next SUSFS patches..."
          cp ../kernel_patches/KernelSU-Next-Implement-SUSFS-v1.5.5-Universal.patch ./
          patch -p1 --forward < KernelSU-Next-Implement-SUSFS-v1.5.5-Universal.patch || true
          

          # Change to common directory and apply SUSFS patch
          cd  ../common
          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch || true
          
          
         
          
      - name: Apply Hide Stuff Patches😘
        run: |
          cd Android-Kernel-Builder          
          # Apply additional patch
          [ ! -f ./kernel_patches/69_hide_stuff.patch ] && exit 1
          cp ./kernel_patches/69_hide_stuff.patch ./common
          cd common
          patch -p1 -F 3 < 69_hide_stuff.patch

      - name: Add SUSFS Configuration Settings😛
        run: |
          cd Android-Kernel-Builder

          echo "Adding configuration settings to gki_defconfig..."

          # Add SUSFS configuration settings
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> ./common/arch/arm64/configs/gki_defconfig

          # Add additional tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig

          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          
      - name: "🎶 Build kernel"
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          echo "PATH Variable: $PATH"
          cd Android-Kernel-Builder
          mkdir -p out/dist
          
          BUILD_CONFIG=common/build.config.gki.aarch64 build/config.sh savedefconfig
          sed -i '$s|echo "\$res"|echo "\$res-Wild+"|' ./common/scripts/setlocalversion
          # Run perl command to modify UTS_VERSION
          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./common/scripts/mkcompile_h
          sed -i 's/-dirty//' ./common/scripts/setlocalversion
          
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh | tee out/dist/build_log.txt
          cd out/dist
          rm -f ./vmlinux ./Image.lz4 ./kernel-headers.tar.gz
          cp $(find .. -name ".config") .
          gzip ./Image
          
      - name: "🥰 Pack artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.kernelName }}
          compression-level: 9
          path: Android-Kernel-Builder/out/dist
